# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoRestAPI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'SWXMLHash', '~> 4.0.0'
  # Pods for DemoRestAPI

  target 'DemoRestAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoRestAPIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
