# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoPKHUD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PKHUD', '~> 5.0'
  # Pods for DemoPKHUD
  
  target 'DemoPKHUDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoPKHUDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
