# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoMQTTProtobuf' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaMQTT'
  pod 'ProtocolBuffers-Swift'

  # Pods for DemoMQTTProtobuf

  target 'DemoMQTTProtobufTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoMQTTProtobufUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
