# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoGoogleMaps' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  # Pods for DemoGoogleMaps

  target 'DemoGoogleMapsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoGoogleMapsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
