# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoTableViewReorder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftReorder', '~> 5.0'
  # Pods for DemoTableViewReorder

  target 'DemoTableViewReorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoTableViewReorderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
