# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoContacts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyContacts' , '~> 2.0.7'


  # Pods for DemoContacts

  target 'DemoContactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoContactsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
