# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoLibPhoneNumber' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'libPhoneNumber-iOS', '~> 0.8'
  # Pods for DemoLibPhoneNumber

  target 'DemoLibPhoneNumberTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoLibPhoneNumberUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
