# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoReachability' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'ReachabilitySwift'
  # Pods for DemoReachability

  target 'DemoReachabilityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoReachabilityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
